-- Your SQL goes here
CREATE TABLE ACTIVITY_TRACKER
(
    ID         BIGSERIAL PRIMARY KEY        NOT NULL,
    CREATED_AT VARCHAR DEFAULT CURRENT_DATE NOT NULL,
    USER_ID    UUID                         NOT NULL,
    CONSTRAINT FK_USERS FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID) ON DELETE CASCADE
);