-- Your SQL goes here
CREATE TABLE ORG_PROJECTS
(
    ID            UUID PRIMARY KEY NOT NULL,
    DISPLAY_NAME  VARCHAR(200)     NOT NULL,
    SETTING       JSON             NOT NULL,
    RELATED_FILES VARCHAR ARRAY    NOT NULL,
    USER_ID       UUID             NOT NULL,
    CREATED_AT    TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_USERS FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID) ON DELETE CASCADE
)