-- Your SQL goes here
CREATE TABLE USERS
(
    ID UUID PRIMARY KEY NOT NULL,
    USERNAME VARCHAR NOT NULL,
    PASSWORD VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL UNIQUE,
    CREATED_AT VARCHAR DEFAULT CURRENT_DATE NOT NULL
)